spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  boot:
    admin:
      client:
        url: [http://localhost:8080]
        username: "admin"
        password: "admin"
        instance:
          metadata:
            user.name: admin
            user.password: admin
  security:
    basic:
      enabled: true
    user:
      name: client
      password: client0

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info, health, metrics, trace
      security:
        enabled: false
    jmx:
      exposure:
        include: info, health, metrics, trace
  endpoint:
    health:
      show-details: always
  port: 9000
